In [2]:
# import libraries
import pandas as pd
import numpy as np
import csv

In [3]:
# Read the csv file to get the Records and all variables
record_list = []
variables = set()

with open('bottom_line_Apple.csv', 'r') as file:
    csvreader = csv.reader(file)
    for row in csvreader:
        if len(row) == 1:
            record_list.append(row[0])
        else:
            row = row[1:]
            for i in range(0,len(row),2):
                variables.add(row[i])

print(record_list)
print(variables)

['Record 683', 'Record 723', 'Record 112', 'Record 245', 'Record 147', 'Record 84', 'Record 119', 'Record 237', 'Record 264', 'Record 152', 'Record 1071', 'Record 80', 'Record 437', 'Record 1001', 'Record 733', 'Record 656', 'Record 425', 'Record 45', 'Record 941', 'Record 383', 'Record 436', 'Record 616', 'Record 19', 'Record 183', 'Record 62', 'Record 73', 'Record 394', 'Record 792', 'Record 625', 'Record 662', 'Record 909', 'Record 246', 'Record 351', 'Record 1028', 'Record 446', 'Record 713', 'Record 749', 'Record 778', 'Record 601', 'Record 797', 'Record 553', 'Record 479', 'Record 655', 'Record 1121', 'Record 562', 'Record 520', 'Record 685', 'Record 781', 'Record 704', 'Record 671', 'Record 345', 'Record 38', 'Record 236', 'Record 666', 'Record 700', 'Record 506', 'Record 1003', 'Record 267', 'Record 400', 'Record 744', 'Record 1027', 'Record 740', 'Record 933', 'Record 1083', 'Record 846', 'Record 841', 'Record 32', 'Record 582', 'Record 1008', 'Record 918', 'Record 547', 'Record 898', 'Record 125', 'Record 122', 'Record 678', 'Record 966', 'Record 161', 'Record 948', 'Record 991', 'Record 220', 'Record 719', 'Record 270', 'Record 376', 'Record 842', 'Record 233', 'Record 218', 'Record 35', 'Record 989', 'Record 512', 'Record 1103', 'Record 803', 'Record 963', 'Record 223', 'Record 788', 'Record 335', 'Record 1038', 'Record 1106', 'Record 318', 'Record 1085', 'Record 157', 'Record 913', 'Record 134', 'Record 333', 'Record 411', 'Record 926', 'Record 16', 'Record 1140', 'Record 827', 'Record 1082', 'Record 1069', 'Record 94', 'Record 612', 'Record 1061', 'Record 342', 'Record 468', 'Record 282', 'Record 360', 'Record 949', 'Record 1', 'Record 613', 'Record 577', 'Record 818', 'Record 974', 'Record 431', 'Record 56', 'Record 210', 'Record 200', 'Record 1095', 'Record 144', 'Record 503', 'Record 906', 'Record 593', 'Record 13', 'Record 946', 'Record 760', 'Record 78', 'Record 1123', 'Record 131', 'Record 374', 'Record 192', 'Record 17', 'Record 928', 'Record 213', 'Record 681', 'Record 336', 'Record 754', 'Record 605', 'Record 428', 'Record 262', 'Record 569', 'Record 310', 'Record 473', 'Record 858', 'Record 296', 'Record 287', 'Record 390', 'Record 1031', 'Record 348', 'Record 67', 'Record 780', 'Record 303', 'Record 892', 'Record 711', 'Record 998', 'Record 1018', 'Record 1050', 'Record 108', 'Record 943', 'Record 385', 'Record 353', 'Record 888', 'Record 1053', 'Record 791', 'Record 159', 'Record 443', 'Record 361', 'Record 893', 'Record 573', 'Record 538', 'Record 561', 'Record 201', 'Record 160', 'Record 1084', 'Record 571', 'Record 249', 'Record 519', 'Record 862', 'Record 197', 'Record 40', 'Record 769', 'Record 291', 'Record 587', 'Record 189', 'Record 145', 'Record 741', 'Record 363', 'Record 1052', 'Record 977', 'Record 513', 'Record 116', 'Record 703', 'Record 454', 'Record 356', 'Record 670', 'Record 354', 'Record 414', 'Record 6', 'Record 1144', 'Record 745', 'Record 378', 'Record 171', 'Record 27', 'Record 794', 'Record 188', 'Record 216', 'Record 163', 'Record 1077', 'Record 349', 'Record 637', 'Record 60', 'Record 1118', 'Record 990', 'Record 1076', 'Record 186', 'Record 162', 'Record 981', 'Record 916', 'Record 368', 'Record 787', 'Record 627', 'Record 1092', 'Record 1066', 'Record 1047', 'Record 622', 'Record 244', 'Record 905', 'Record 463', 'Record 668', 'Record 572', 'Record 523', 'Record 1020', 'Record 283', 'Record 177', 'Record 775', 'Record 452', 'Record 501', 'Record 226', 'Record 1062', 'Record 586', 'Record 448', 'Record 550', 'Record 462', 'Record 899', 'Record 746', 'Record 1065', 'Record 397', 'Record 277', 'Record 402', 'Record 602', 'Record 708', 'Record 694', 'Record 301', 'Record 1035', 'Record 165', 'Record 493', 'Record 379', 'Record 884', 'Record 7', 'Record 290', 'Record 2', 'Record 881', 'Record 813', 'Record 782', 'Record 334', 'Record 525', 'Record 556', 'Record 173', 'Record 938', 'Record 364', 'Record 120', 'Record 248', 'Record 521', 'Record 164', 'Record 219', 'Record 845', 'Record 47', 'Record 755', 'Record 1000', 'Record 815', 'Record 595', 'Record 151', 'Record 669', 'Record 234', 'Record 750', 'Record 1070', 'Record 1080', 'Record 298', 'Record 90', 'Record 341', 'Record 939', 'Record 486', 'Record 903', 'Record 263', 'Record 808', 'Record 579', 'Record 819', 'Record 433', 'Record 435', 'Record 743', 'Record 288', 'Record 181', 'Record 987', 'Record 350', 'Record 1113', 'Record 563', 'Record 491', 'Record 97', 'Record 774', 'Record 339', 'Record 464', 'Record 72', 'Record 26', 'Record 453', 'Record 250', 'Record 961', 'Record 1036', 'Record 534', 'Record 822', 'Record 212', 'Record 449', 'Record 82', 'Record 498', 'Record 1063', 'Record 1099', 'Record 1045', 'Record 92', 'Record 527', 'Record 1114', 'Record 9', 'Record 1011', 'Record 583', 'Record 313', 'Record 836', 'Record 4', 'Record 113', 'Record 1124', 'Record 344', 'Record 962', 'Record 752', 'Record 887', 'Record 102', 'Record 75', 'Record 445', 'Record 1152', 'Record 1059', 'Record 509', 'Record 30', 'Record 292', 'Record 1072', 'Record 1034', 'Record 585', 'Record 695', 'Record 408', 'Record 1075', 'Record 158', 'Record 439', 'Record 227', 'Record 927', 'Record 779', 'Record 127', 'Record 387', 'Record 484', 'Record 111', 'Record 86', 'Record 524', 'Record 821', 'Record 699', 'Record 142', 'Record 128', 'Record 202', 'Record 950', 'Record 535', 'Record 584', 'Record 179', 'Record 576', 'Record 728', 'Record 642', 'Record 169', 'Record 22', 'Record 393', 'Record 614', 'Record 59', 'Record 1029', 'Record 1051', 'Record 504', 'Record 417', 'Record 478', 'Record 312', 'Record 88', 'Record 139', 'Record 767', 'Record 647', 'Record 952', 'Record 307', 'Record 232', 'Record 488', 'Record 607', 'Record 650', 'Record 343', 'Record 665', 'Record 284', 'Record 476', 'Record 1088', 'Record 777', 'Record 880', 'Record 317', 'Record 118', 'Record 1116', 'Record 924', 'Record 968', 'Record 930', 'Record 12', 'Record 758', 'Record 856', 'Record 896', 'Record 514', 'Record 375', 'Record 868', 'Record 663', 'Record 867', 'Record 221', 'Record 206', 'Record 580', 'Record 537', 'Record 471', 'Record 496', 'Record 458', 'Record 93', 'Record 575', 'Record 693', 'Record 828', 'Record 762', 'Record 427', 'Record 259', 'Record 149', 'Record 438', 'Record 945', 'Record 415', 'Record 630', 'Record 295', 'Record 130', 'Record 146', 'Record 459', 'Record 235', 'Record 1127', 'Record 199', 'Record 848', 'Record 136', 'Record 589', 'Record 1024', 'Record 485', 'Record 1021', 'Record 996', 'Record 1078', 'Record 567', 'Record 1006', 'Record 1097', 'Record 265', 'Record 823', 'Record 988', 'Record 380', 'Record 854', 'Record 101', 'Record 624', 'Record 552', 'Record 230', 'Record 1009', 'Record 686', 'Record 919', 'Record 1138', 'Record 261', 'Record 33', 'Record 1120', 'Record 297', 'Record 979', 'Record 405', 'Record 863', 'Record 908', 'Record 516', 'Record 389', 'Record 814', 'Record 860', 'Record 773', 'Record 1119', 'Record 969', 'Record 915', 'Record 194', 'Record 560', 'Record 25', 'Record 322', 'Record 410', 'Record 39', 'Record 426', 'Record 837', 'Record 829', 'Record 190', 'Record 1107', 'Record 772', 'Record 765', 'Record 475', 'Record 651', 'Record 1023', 'Record 1042', 'Record 54', 'Record 44', 'Record 306', 'Record 1109', 'Record 902', 'Record 594', 'Record 399', 'Record 121', 'Record 57', 'Record 347', 'Record 1015', 'Record 890', 'Record 995', 'Record 472', 'Record 55', 'Record 682', 'Record 370', 'Record 734', 'Record 972', 'Record 954', 'Record 570', 'Record 720', 'Record 29', 'Record 790', 'Record 763', 'Record 531', 'Record 687', 'Record 676', 'Record 401', 'Record 784', 'Record 578', 'Record 64', 'Record 921', 'Record 866', 'Record 1014', 'Record 66', 'Record 947', 'Record 41', 'Record 761', 'Record 28', 'Record 831', 'Record 975', 'Record 555', 'Record 1134', 'Record 809', 'Record 633', 'Record 610', 'Record 46', 'Record 805', 'Record 69', 'Record 257', 'Record 900', 'Record 195', 'Record 398', 'Record 43', 'Record 515', 'Record 727', 'Record 129', 'Record 1150', 'Record 657', 'Record 581', 'Record 191', 'Record 358', 'Record 1135', 'Record 545', 'Record 835', 'Record 178', 'Record 211', 'Record 10', 'Record 935', 'Record 967', 'Record 362', 'Record 208', 'Record 300', 'Record 820', 'Record 853', 'Record 674', 'Record 309', 'Record 124', 'Record 922', 'Record 98', 'Record 31', 'Record 1064', 'Record 911', 'Record 658', 'Record 716', 'Record 759', 'Record 748', 'Record 937', 'Record 770', 'Record 804', 'Record 645', 'Record 714', 'Record 632', 'Record 140', 'Record 95', 'Record 732', 'Record 89', 'Record 982', 'Record 1007', 'Record 451', 'Record 511', 'Record 606', 'Record 269', 'Record 796', 'Record 965', 'Record 340', 'Record 510', 'Record 70', 'Record 388', 'Record 609', 'Record 904', 'Record 959', 'Record 558', 'Record 709', 'Record 1098', 'Record 327', 'Record 308', 'Record 217', 'Record 1126', 'Record 1139', 'Record 272', 'Record 1022', 'Record 492', 'Record 321', 'Record 768', 'Record 832', 'Record 53', 'Record 182', 'Record 914', 'Record 359', 'Record 109', 'Record 795', 'Record 255', 'Record 724', 'Record 222', 'Record 23', 'Record 833', 'Record 843', 'Record 735', 'Record 882', 'Record 592', 'Record 942', 'Record 675', 'Record 528', 'Record 604', 'Record 1105', 'Record 20', 'Record 1033', 'Record 646', 'Record 565', 'Record 793', 'Record 964', 'Record 812', 'Record 889', 'Record 123', 'Record 241', 'Record 229', 'Record 557', 'Record 1149', 'Record 691', 'Record 859', 'Record 440', 'Record 739', 'Record 597', 'Record 99', 'Record 971', 'Record 677', 'Record 785', 'Record 912', 'Record 352', 'Record 205', 'Record 1032', 'Record 209', 'Record 783', 'Record 953', 'Record 1055', 'Record 314', 'Record 936', 'Record 738', 'Record 450', 'Record 1094', 'Record 999', 'Record 1133', 'Record 551', 'Record 196', 'Record 487', 'Record 419', 'Record 986', 'Record 326', 'Record 574', 'Record 1058', 'Record 667', 'Record 857', 'Record 1110', 'Record 404', 'Record 465', 'Record 786', 'Record 931', 'Record 541', 'Record 544', 'Record 536', 'Record 103', 'Record 849', 'Record 42', 'Record 894', 'Record 107', 'Record 50', 'Record 406', 'Record 799', 'Record 51', 'Record 100', 'Record 377', 'Record 951', 'Record 844', 'Record 940', 'Record 619', 'Record 543', 'Record 258', 'Record 457', 'Record 497', 'Record 1004', 'Record 1101', 'Record 61', 'Record 508', 'Record 620', 'Record 718', 'Record 481', 'Record 204', 'Record 1117', 'Record 798', 'Record 970', 'Record 138', 'Record 764', 'Record 305', 'Record 878', 'Record 934', 'Record 776', 'Record 631', 'Record 1143', 'Record 1146', 'Record 690', 'Record 76', 'Record 810', 'Record 753', 'Record 420', 'Record 891', 'Record 901', 'Record 869', 'Record 886', 'Record 403', 'Record 366', 'Record 444', 'Record 588', 'Record 865', 'Record 442', 'Record 79', 'Record 49', 'Record 474', 'Record 824', 'Record 156', 'Record 529', 'Record 203', 'Record 617', 'Record 413', 'Record 980', 'Record 365', 'Record 1054', 'Record 629', 'Record 1060', 'Record 852', 'Record 697', 'Record 689', 'Record 1148', 'Record 477', 'Record 58', 'Record 117', 'Record 242', 'Record 1141', 'Record 705', 'Record 1037', 'Record 1125', 'Record 239', 'Record 960', 'Record 331', 'Record 423', 'Record 167', 'Record 409', 'Record 1013', 'Record 83', 'Record 701', 'Record 154', 'Record 507', 'Record 993', 'Record 278', 'Record 424', 'Record 1046', 'Record 180', 'Record 1090', 'Record 316', 'Record 455', 'Record 470', 'Record 280', 'Record 653', 'Record 757', 'Record 698', 'Record 482', 'Record 63', 'Record 483', 'Record 564', 'Record 332', 'Record 640', 'Record 155', 'Record 1137', 'Record 1049', 'Record 696', 'Record 490', 'Record 883', 'Record 559', 'Record 1104', 'Record 36', 'Record 3', 'Record 275', 'Record 879', 'Record 65', 'Record 434', 'Record 688', 'Record 1102', 'Record 591', 'Record 338', 'Record 907', 'Record 104', 'Record 638', 'Record 1073', 'Record 840', 'Record 311', 'Record 1043', 'Record 985', 'Record 1093', 'Record 789', 'Record 253', 'Record 330', 'Record 252', 'Record 52', 'Record 634', 'Record 1122', 'Record 984', 'Record 412', 'Record 286', 'Record 929', 'Record 807', 'Record 957', 'Record 15', 'Record 281', 'Record 430', 'Record 1030', 'Record 864', 'Record 920', 'Record 636', 'Record 615', 'Record 289', 'Record 271', 'Record 302', 'Record 396', 'Record 106', 'Record 407', 'Record 357', 'Record 325', 'Record 1067', 'Record 266', 'Record 1044', 'Record 874', 'Record 1151', 'Record 87', 'Record 1017', 'Record 1111', 'Record 5', 'Record 137', 'Record 8', 'Record 168', 'Record 85', 'Record 299', 'Record 1142', 'Record 371', 'Record 811', 'Record 391', 'Record 598', 'Record 172', 'Record 166', 'Record 725', 'Record 74', 'Record 1041', 'Record 801', 'Record 1012', 'Record 1026', 'Record 382', 'Record 639', 'Record 1086', 'Record 256', 'Record 14', 'Record 826', 'Record 247', 'Record 372', 'Record 747', 'Record 641', 'Record 392', 'Record 268', 'Record 441', 'Record 766', 'Record 135', 'Record 737', 'Record 115', 'Record 712', 'Record 626', 'Record 175', 'Record 707', 'Record 522', 'Record 1147', 'Record 1010', 'Record 170', 'Record 932', 'Record 992', 'Record 672', 'Record 679', 'Record 273', 'Record 684', 'Record 706', 'Record 466', 'Record 24', 'Record 228', 'Record 1019', 'Record 834', 'Record 855', 'Record 214', 'Record 885', 'Record 21', 'Record 500', 'Record 285', 'Record 71', 'Record 644', 'Record 132', 'Record 895', 'Record 611', 'Record 320', 'Record 533', 'Record 502', 'Record 251', 'Record 983', 'Record 729', 'Record 91', 'Record 659', 'Record 198', 'Record 499', 'Record 184', 'Record 726', 'Record 539', 'Record 847', 'Record 1100', 'Record 367', 'Record 243', 'Record 730', 'Record 225', 'Record 731', 'Record 839', 'Record 722', 'Record 1074', 'Record 956', 'Record 806', 'Record 207', 'Record 702', 'Record 871', 'Record 373', 'Record 337', 'Record 599', 'Record 176', 'Record 1145', 'Record 532', 'Record 861', 'Record 955', 'Record 384', 'Record 526', 'Record 133', 'Record 505', 'Record 231', 'Record 48', 'Record 315', 'Record 851', 'Record 1079', 'Record 1002', 'Record 715', 'Record 1091', 'Record 1089', 'Record 751', 'Record 628', 'Record 648', 'Record 802', 'Record 817', 'Record 105', 'Record 566', 'Record 680', 'Record 1096', 'Record 34', 'Record 153', 'Record 432', 'Record 736', 'Record 603', 'Record 673', 'Record 876', 'Record 422', 'Record 467', 'Record 456', 'Record 1081', 'Record 96', 'Record 549', 'Record 530', 'Record 294', 'Record 870', 'Record 447', 'Record 830', 'Record 369', 'Record 429', 'Record 293', 'Record 495', 'Record 494', 'Record 37', 'Record 994', 'Record 1129', 'Record 11', 'Record 596', 'Record 1108', 'Record 324', 'Record 150', 'Record 875', 'Record 958', 'Record 850', 'Record 1131', 'Record 692', 'Record 710', 'Record 976', 'Record 1128', 'Record 923', 'Record 873', 'Record 978', 'Record 1057', 'Record 126', 'Record 771', 'Record 460', 'Record 917', 'Record 114', 'Record 997', 'Record 661', 'Record 717', 'Record 110', 'Record 329', 'Record 274', 'Record 742', 'Record 1115', 'Record 185', 'Record 174', 'Record 546', 'Record 635', 'Record 355', 'Record 872', 'Record 421', 'Record 416', 'Record 1039', 'Record 877', 'Record 254', 'Record 328', 'Record 721', 'Record 621', 'Record 1132', 'Record 386', 'Record 279', 'Record 654', 'Record 148', 'Record 395', 'Record 224', 'Record 664', 'Record 643', 'Record 517', 'Record 944', 'Record 1130', 'Record 816', 'Record 1056', 'Record 346', 'Record 1040', 'Record 652', 'Record 910', 'Record 590', 'Record 548', 'Record 238', 'Record 1025', 'Record 461', 'Record 193', 'Record 618', 'Record 1068', 'Record 1087', 'Record 897', 'Record 542', 'Record 469', 'Record 1136', 'Record 838', 'Record 608', 'Record 81', 'Record 925', 'Record 800', 'Record 304', 'Record 480', 'Record 141', 'Record 600', 'Record 1112', 'Record 143', 'Record 18', 'Record 518', 'Record 540', 'Record 1005', 'Record 77', 'Record 319', 'Record 260', 'Record 215', 'Record 418', 'Record 1016', 'Record 973', 'Record 825', 'Record 623', 'Record 381', 'Record 323', 'Record 756', 'Record 1048', 'Record 240', 'Record 660', 'Record 489', 'Record 276', 'Record 68', 'Record 187', 'Record 554', 'Record 568', 'Record 649']
{'', '% Democrats', '% White', 'Rainfall (Inches)', 'Num. Employees', 'Population (000s)', '% Home Owners', 'Avg. Household Size', '% Female', 'Log Price', 'Year', 'Avg. Commute (mins)', 'Avg. Age', 'Unemployment Rate', 'Avg. Employee Wage (000s)', 'Num. BestBuy', 'Avg. Income (000s)', 'Log Profit', 'County', 'Num. Krogers', 'Month', 'Avg. Education (Yrs.)'}

In [4]:
# convert record_list to panda Series
record = pd.Series(record_list, name='Record')
record

0       Record 683
1       Record 723
2       Record 112
3       Record 245
4       Record 147
           ...
1147     Record 68
1148    Record 187
1149    Record 554
1150    Record 568
1151    Record 649
Name: Record, Length: 1152, dtype: object

In [5]:
# convert Series into dataframe
# initalize all variables into the dataframe
df = pd.DataFrame(record, columns=['Record'])

variables = sorted(variables)

for variable in variables:
    df[variable] = [''] * len(df)

df

,Record,,% Democrats,% Female,% Home Owners,% White,Avg. Age,Avg. Commute (mins),Avg. Education (Yrs.),Avg. Employee Wage (000s),...,Log Price,Log Profit,Month,Num. BestBuy,Num. Employees,Num. Krogers,Population (000s),Rainfall (Inches),Unemployment Rate,Year
0,Record 683,,,,,,,,,,...,,,,,,,,,,
1,Record 723,,,,,,,,,,...,,,,,,,,,,
2,Record 112,,,,,,,,,,...,,,,,,,,,,
3,Record 245,,,,,,,,,,...,,,,,,,,,,
4,Record 147,,,,,,,,,,...,,,,,,,,,,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1147,Record 68,,,,,,,,,,...,,,,,,,,,,
1148,Record 187,,,,,,,,,,...,,,,,,,,,,
1149,Record 554,,,,,,,,,,...,,,,,,,,,,
1150,Record 568,,,,,,,,,,...,,,,,,,,,,
1151,Record 649,,,,,,,,,,...,,,,,,,,,,

In [6]:
# read the csv file again and fill the dataframe

dict = {}
current_record = ''

# Function to add values to the dataframe based on the current record
def add_to_df(current_record, df, dict):
    if dict.keys() == []:  # if dict is empty, do not proceed
        return
    if current_record in df['Record'].values:
        for variable, value in dict.items():
            df.loc[df['Record'] == current_record, variable] = value


with open('bottom_line_Apple.csv', 'r') as file:
    csvreader = csv.reader(file)
    for row in csvreader:
        if len(row) == 1: # if the row has only one element, it is a record name
            if current_record != '': # check if current_record is not empty
                add_to_df(current_record, df, dict)
                dict = {}
            current_record = row[0]
        else:
            row = row[1:] # remove the first element which is the record name or empty string
            for i in range(0, len(row), 2):
                variable = row[i]
                value = row[i + 1] if i + 1 < len(row) else ''
                dict[variable] = value
    add_to_df(current_record, df, dict)

In [7]:
df.drop('', axis=1, inplace=True)
df

,Record,% Democrats,% Female,% Home Owners,% White,Avg. Age,Avg. Commute (mins),Avg. Education (Yrs.),Avg. Employee Wage (000s),Avg. Household Size,...,Log Price,Log Profit,Month,Num. BestBuy,Num. Employees,Num. Krogers,Population (000s),Rainfall (Inches),Unemployment Rate,Year
0,Record 683,0.586943601181,0.520913741363,0.226260862473,0.885829582958,51.0,63.0,10.0,177.542318395,1.0,...,6.88341960583,5.53139631254,3.0,3.0,8.0,3.0,167.138856935,4.11741891327,0.0742276991469,2017.0
1,Record 723,0.589980621429,0.527758339855,0.592413901364,0.584800608234,57.0,25.0,20.0,49.3057206359,6.0,...,5.42115461996,8.54965993045,1.0,0.0,5.0,0.0,99.9694058023,6.53233587235,0.092409914271,2017.0
2,Record 112,0.223278681483,0.565790352693,0.605265942107,0.233687203965,49.0,64.0,14.0,69.1560476878,1.0,...,7.6174416219,2.02213656621,4.0,4.0,11.0,6.0,206.903386992,7.6596386439,0.024580563115,2018.0
3,Record 245,0.481817344472,0.448915718282,0.308268322964,0.581420680321,69.0,58.0,7.0,156.63315357,6.0,...,5.6698542114,10.1556897074,2.0,4.0,9.0,2.0,215.376341452,2.47944523022,0.0218831140355,2015.0
4,Record 147,0.631889953722,0.479173903072,0.667278074132,0.612639093344,71.0,36.0,13.0,174.250944427,3.0,...,5.92692545129,9.93588637169,1.0,2.0,14.0,2.0,286.436487977,6.53704237966,0.03160700373,2017.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1147,Record 68,0.0103626104327,0.481589416919,0.649524507777,0.155447738033,65.0,61.0,6.0,4.01265165544,8.0,...,7.62721575733,4.30069608807,5.0,0.0,1.0,1.0,43.1721813697,4.82477721051,0.199325965723,2018.0
1148,Record 187,0.410338070604,0.552281614967,0.646621078455,0.00800946837773,54.0,7.0,14.0,90.8201025048,7.0,...,3.73904744887,17.944744349,11.0,3.0,6.0,1.0,164.910636215,9.24415504547,0.055413531689,2017.0
1149,Record 554,0.0790216404382,0.439555144538,0.61395268154,0.0630412052052,70.0,23.0,6.0,60.7988562521,7.0,...,9.60903658923,-2.44924685463,7.0,2.0,13.0,2.0,294.635370044,9.56335044243,0.146922625111,2016.0
1150,Record 568,0.0103931157327,0.447862939663,0.488104577323,0.576906181817,64.0,67.0,15.0,155.27745399,8.0,...,9.0696921555,-11.282816506,10.0,0.0,1.0,0.0,8.62136484959,3.04367527054,0.184513202459,2018.0
1151,Record 649,0.170341607727,0.440813309215,0.374740143604,0.40705075047,42.0,20.0,15.0,14.7913653352,6.0,...,8.3185868738,7.06037547104,7.0,2.0,11.0,10.0,271.680570273,7.52547380091,0.158118432733,2015.0

In [8]:
# dataframe cleaning
df['Record'] = df['Record'].str.split(' ').str[1]
df

,Record,% Democrats,% Female,% Home Owners,% White,Avg. Age,Avg. Commute (mins),Avg. Education (Yrs.),Avg. Employee Wage (000s),Avg. Household Size,...,Log Price,Log Profit,Month,Num. BestBuy,Num. Employees,Num. Krogers,Population (000s),Rainfall (Inches),Unemployment Rate,Year
0,683,0.586943601181,0.520913741363,0.226260862473,0.885829582958,51.0,63.0,10.0,177.542318395,1.0,...,6.88341960583,5.53139631254,3.0,3.0,8.0,3.0,167.138856935,4.11741891327,0.0742276991469,2017.0
1,723,0.589980621429,0.527758339855,0.592413901364,0.584800608234,57.0,25.0,20.0,49.3057206359,6.0,...,5.42115461996,8.54965993045,1.0,0.0,5.0,0.0,99.9694058023,6.53233587235,0.092409914271,2017.0
2,112,0.223278681483,0.565790352693,0.605265942107,0.233687203965,49.0,64.0,14.0,69.1560476878,1.0,...,7.6174416219,2.02213656621,4.0,4.0,11.0,6.0,206.903386992,7.6596386439,0.024580563115,2018.0
3,245,0.481817344472,0.448915718282,0.308268322964,0.581420680321,69.0,58.0,7.0,156.63315357,6.0,...,5.6698542114,10.1556897074,2.0,4.0,9.0,2.0,215.376341452,2.47944523022,0.0218831140355,2015.0
4,147,0.631889953722,0.479173903072,0.667278074132,0.612639093344,71.0,36.0,13.0,174.250944427,3.0,...,5.92692545129,9.93588637169,1.0,2.0,14.0,2.0,286.436487977,6.53704237966,0.03160700373,2017.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1147,68,0.0103626104327,0.481589416919,0.649524507777,0.155447738033,65.0,61.0,6.0,4.01265165544,8.0,...,7.62721575733,4.30069608807,5.0,0.0,1.0,1.0,43.1721813697,4.82477721051,0.199325965723,2018.0
1148,187,0.410338070604,0.552281614967,0.646621078455,0.00800946837773,54.0,7.0,14.0,90.8201025048,7.0,...,3.73904744887,17.944744349,11.0,3.0,6.0,1.0,164.910636215,9.24415504547,0.055413531689,2017.0
1149,554,0.0790216404382,0.439555144538,0.61395268154,0.0630412052052,70.0,23.0,6.0,60.7988562521,7.0,...,9.60903658923,-2.44924685463,7.0,2.0,13.0,2.0,294.635370044,9.56335044243,0.146922625111,2016.0
1150,568,0.0103931157327,0.447862939663,0.488104577323,0.576906181817,64.0,67.0,15.0,155.27745399,8.0,...,9.0696921555,-11.282816506,10.0,0.0,1.0,0.0,8.62136484959,3.04367527054,0.184513202459,2018.0
1151,649,0.170341607727,0.440813309215,0.374740143604,0.40705075047,42.0,20.0,15.0,14.7913653352,6.0,...,8.3185868738,7.06037547104,7.0,2.0,11.0,10.0,271.680570273,7.52547380091,0.158118432733,2015.0

In [9]:
# export cleaned csv
df.to_csv('bottom_line_Apple_cleaned.csv', index=False)